workflows:
  ios_build:
    name: iOS Build Workflow
    environment:
      xcode: "16.0"  # Setze die Xcode-Version auf 16.0
      flutter: "3.0"  # Verwende die Flutter-Version, die du benötigst
    scripts:
      - flutter pub get  # Holt alle benötigten Abhängigkeiten
      - flutter build ios --release  # Baut das iOS-Projekt im Release-Modus
    artifacts:
      - build/ios/iphoneos/*.ipa  # Definiert das Artefakt, das erstellt wird
