workflows:
  ios_build:
    name: iOS Build Workflow
    environment:
      xcode: "13.0"  # Definiert die Xcode-Version
      flutter: "3.0"  # Flutter Version
    script:
      # Holen von Abhängigkeiten
      - flutter pub get
      # Build für iOS
      - flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.ipa  # Beispiel für die IPA-Datei als Artefakt
