workflows:
  ios_build:
    name: Build iOS for Testing
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - cd src/OpenWebUI  # Wechsel zum richtigen Verzeichnis
      - flutter pub get
      - flutter build ios --no-codesign