workflows:
  ios_build:
    name: iOS Build Workflow
    environment:
      xcode: "12.5.1"  # Verwende eine unterstützte Xcode-Version
      flutter: "3.0"    # Verwende die Flutter-Version, die du benötigst
    scripts:
      - flutter pub get  # Holt alle benötigten Abhängigkeiten
      - flutter build ios --release  # Baut das iOS-Projekt im Release-Modus
    artifacts:
      - build/ios/iphoneos/*.ipa  # Definiert das Artefakt, das erstellt wird
